name: Build, Package, and Release

on:
  push:
    branches: [ 'main' ]
    paths:
      - 'src/**'
      - '!.github/**'
      - '!docs/**'
      - '!tests/**'
      - '!README.md'
      - '!CHANGELOG.md'
      - '!CODE_OF_CONDUCT.md'
      - '!SECURITY.md'
      - '!LICENSE'
      - '!CONTRIBUTING.md'

  workflow_dispatch:
  # pull_request:
  #   branches: [ main ]
  #   types: [closed]
  #   paths:
  #     - 'EmailModule/**'
  #     - 'EmailLibraryDesktop/**'
  #     - 'EmailLibraryCore/**'
  #     - '!.github/workflows/**'
  #     - '!README.md'
  #     - '!.wiki/**'

permissions:
  contents: write

jobs:
  build:
    environment: Build Package and Release
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup MSBuild .NET Framework Build
        uses: microsoft/setup-msbuild@v2.0.0

      - name: Setup NuGet .NET Framework Build
        uses: nuget/setup-nuget@v2
        with:
          nuget-version: 'latest'

      - name: Restore NuGet packages for .NET Framework Build
        run: nuget restore .\src\EmailLibraryDesktop\EmailLibrary.sln

      - name: Build .NET Framework project
        run: |
          msbuild .\src\EmailLibraryDesktop\EmailLibrary.sln /p:Configuration=Release /p:Platform="Any CPU" /p:TargetFrameworkVersion="v4.7.2"

      - name: Create release directories
        run: |
          $version = '${{ steps.tag_version.outputs.new_tag }}'
          $version = $version  -replace 'v', ''
          New-Item -ItemType Directory -Path release | Out-Null;
          New-Item -ItemType Directory -Path .\release\EmailModule | Out-Null;
          New-Item -ItemType Directory -Path .\release\EmailModule\$version | Out-Null;
          New-Item -ItemType Directory -Path .\release\EmailModule\$version\lib | Out-Null;
          New-Item -ItemType Directory -Path .\release\EmailModule\$version\lib\net8.0 | Out-Null;
          New-Item -ItemType Directory -Path .\release\EmailModule\$version\lib\net472 | Out-Null;

      - name: Copy .NET Framework build output to lib Desktop directory
        run: |
          $version = '${{ steps.tag_version.outputs.new_tag }}'
          $version = $version  -replace 'v', ''
          $exclude = @(
            'System.Formats.Asn1.dll',
            'Microsoft.Bcl.AsyncInterfaces.dll',
            'Microsoft.Extensions.DependencyInjection.Abstractions.dll',
            'Microsoft.Extensions.Hosting.Abstractions.dll',
            'Microsoft.Extensions.Logging.Abstractions.dll',
            'Microsoft.Extensions.Primitives.dll',
            'System.Diagnostics.DiagnosticSource.dll',
            'System.Text.Encodings.Web.dll',
            'Microsoft.Extensions.WebEncoders.dll'
          )
          Get-ChildItem -path ".\src\EmailLibraryDesktop\EmailLibrary\bin\Release\" -Recurse -Exclude "*.pdb" | Where-Object { $_.Name -notin $exclude } | ForEach-Object {
            Copy-Item $_ -Destination ".\release\EmailModule\$version\lib\net472\"
          }

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: "8.0.x"

      - name: Install dependencies .NET Core Build
        run: dotnet restore .\src\EmailLibraryCore\EmailLibrary\EmailLibrary.csproj

      - name: Publish .NET Core project
        run: dotnet publish .\src\EmailLibraryCore\EmailLibrary\EmailLibrary.csproj --configuration Release --no-restore --output publish
        env:
            PublishRelease: true

      - name: Copy .NET Core publish output to lib Core directory
        run: |
          $version = '${{ steps.tag_version.outputs.new_tag }}'
          $version = $version  -replace 'v', ''
          Get-ChildItem -path ".\publish\" -Exclude "*.pdb" | Where-Object Attributes -ne Directory | ForEach-Object {
            Copy-Item $_ -Destination ".\release\EmailModule\$version\lib\net8.0\"
          }

      - name: Generate Powershell Manifest
        run: |
          $version = '${{ steps.tag_version.outputs.new_tag }}'
          $version = $version  -replace 'v', ''

          $files = @('.\EmailModule.psd1','.\EmailModule.psm1','.\EmailModule.Libraries.ps1',".\EmailModule.nuspec",".\EmailModule.$version.nupkg")
          Get-ChildItem -Path ".\release\EmailModule\$version\" -Recurse -File | ForEach-Object { 
              $files += $_.FullName.ToString().Replace("D:\a\Powershell_Email-Module\Powershell_Email-Module\release\EmailModule\$version",'.') 
          }

          $moduleSettings = @{
            Path = '.\src\EmailModule\EmailModule.psd1'

            # Script module or binary module file associated with this manifest.
            RootModule = 'EmailModule.psm1'

            # Version number of this module.
            ModuleVersion = $version

            # Supported PSEditions
            CompatiblePSEditions = @('Desktop','Core')

            # ID used to uniquely identify this module
            GUID = '6f8c4c8a-6e0d-4139-836c-f798b30ada92'

            # Author of this module
            Author = 'Brandon Navarro'

            # Company or vendor of this module
            CompanyName = 'None'

            # Copyright statement for this module
            Copyright = '(c) Brandon Navarro. All rights reserved.'

            # Description of the functionality provided by this module
            Description = 'Powershell Module to send Email using MailKit, MimeKit and STARTTLS'

            # Minimum version of the PowerShell engine required by this module
            PowerShellVersion = '5.1'

            # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
            DotNetFrameworkVersion = '4.7.2'

            # Processor architecture (None, X86, Amd64) required by this module
            ProcessorArchitecture = 'None'

            # Script files (.ps1) that are run in the caller's environment prior to importing this module.
            ScriptsToProcess = @('EmailModule.Libraries.ps1')

            # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
            FunctionsToExport = @('Send-Email','Get-MimeMessage')

            # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
            CmdletsToExport = @('Send-Email','Get-MimeMessage')

            # Variables to export from this module
            VariablesToExport = @()

            # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
            AliasesToExport = @()

            # List of all files packaged with this module
            FileList = $files

            # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
            Tags        = @('Desktop','Core','Email','StartTLS')
            LicenseUri  = 'https://github.com/Brandon-J-Navarro/Powershell_Email-Module/blob/main/LICENSE'
            ProjectUri  = 'https://github.com/Brandon-J-Navarro/Powershell_Email-Module'
            IconUri     = 'https://github.com/Brandon-J-Navarro/'
            ReleaseNotes = 'Visit GitHub repo for release note / change log'
          }
          New-ModuleManifest @moduleSettings

      - name: Copy powershell module and misc. files to release directory
        run: |
          $version = '${{ steps.tag_version.outputs.new_tag }}'
          $version = $version  -replace 'v', ''
          Copy-Item -Path ".\src\EmailModule\EmailModule.Libraries.ps1" -Destination ".\release\EmailModule\$version\"
          Copy-Item -Path ".\src\EmailModule\EmailModule.psd1" -Destination ".\release\EmailModule\$version\"
          Copy-Item -Path ".\src\EmailModule\EmailModule.psm1" -Destination ".\release\EmailModule\$version\"
          Copy-Item -Path ".\README.md" -Destination ".\release\EmailModule\$version\"
          Copy-Item -Path ".\LICENSE" -Destination ".\release\EmailModule\$version\"

      - name: Generate nuspec
        run: |
          $version = '${{ steps.tag_version.outputs.new_tag }}'
          $version = $version  -replace 'v', ''
          @"
          <?xml version="1.0" encoding="utf-8"?>
          <package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
            <metadata>
              <id>EmailModule</id>
              <version>$version</version>
              <title>EmailModule</title>
              <authors>Brandon Navarro</authors>
              <owners>Brandon Navarro</owners>
              <requireLicenseAcceptance>false</requireLicenseAcceptance>
              <license type="file">LICENSE</license>
              <projectUrl>https://github.com/Brandon-J-Navarro/Powershell_Email-Module</projectUrl>
              <repository type="git" url="https://github.com/Brandon-J-Navarro/Powershell_Email-Module.git" branch="main"/>
              <description>Powershell Module to send Email using MailKit, MimeKit and STARTTLS</description>
              <summary>A brief summary of your module.</summary>
              <releaseNotes>Visit GitHub repo for release note / change log</releaseNotes>
              <readme>README.md</readme>
              <copyright>(c) Brandon Navarro. All rights reserved.</copyright>
              <tags>Desktop Core Email StartTLS</tags>
              <dependencies>
                <group targetFramework=".NETFramework4.7.2">
                  <dependency id="BouncyCastle.Cryptography" version="2.0.0.0" />
                  <dependency id="EmailLibrary" version="1.0.0.0" />
                  <dependency id="MailKit" version="4.17.0.0" />
                  <dependency id="MimeKit" version="4.17.0.0" />
                  <dependency id="System.Buffers" version="4.0.4.0" />
                  <dependency id="System.Formats.Asn1" version="8.0.0.1" />
                  <dependency id="System.Memory" version="4.0.2.0" />
                  <dependency id="System.Numerics.Vectors" version="4.1.5.0" />
                  <dependency id="System.Runtime.CompilerServices.Unsafe" version="6.0.1.0" />
                  <dependency id="System.Threading.Tasks.Extensions" version="4.2.1.0" />
                  <dependency id="System.ValueTuple" version="4.0.3.0" />
                </group>
                <group targetFramework="net8.0">
                  <dependency id="BouncyCastle.Cryptography" version="2.0.0.0" />
                  <dependency id="EmailLibrary" version="1.0.0.0" />
                  <dependency id="MailKit" version="4.17.0" />
                  <dependency id="MimeKit" version="4.17.0" />
                  <dependency id="System.Security.Cryptography.Pkcs" version="8.0.0.0" />
                </group>
              </dependencies>
            </metadata>
            <files>
              <file src=".\**" target="\" />
            </files>
          </package>
          "@ | Out-File -FilePath ".\release\EmailModule\$version\EmailModule.nuspec"

      - name: Build NuGet Package
        run: |
          $version = '${{ steps.tag_version.outputs.new_tag }}'
          $version = $version  -replace 'v', ''
          nuget pack .\release\EmailModule\$version\EmailModule.nuspec -Properties Configuration=Release

      # - name: Publish NuGet Package
      #   run: |
      #     $version = '${{ steps.tag_version.outputs.new_tag }}'
      #     $version = $version  -replace 'v', ''
      #     Copy-Item -Path ".\EmailModule.$version.nupkg" -Destination ".\release\EmailModule\$version\"
      #     dotnet nuget add source https://nuget.pkg.github.com/Brandon-J-Navarro/index.json --name github --username Brandon-J-Navarro --password ${{ secrets.PACKAGE_TOKEN }}
      #     dotnet nuget push ".\EmailModule.$version.nupkg" --api-key ${{ secrets.PACKAGE_TOKEN }} --source "github"

      - name: Zip the release directory
        run: |
          $version = '${{ steps.tag_version.outputs.new_tag }}'
          $version = $version  -replace 'v', ''
          Get-ChildItem -path ".\release\EmailModule\$version\" -Recurse -File | ForEach-Object {
            Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256 | FL | Out-File -FilePath ".\Hashes.txt" -Append
          }
          Compress-Archive -Path ".\release\EmailModule\$version\*" -DestinationPath "EmailModule.zip"

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1.20.0
        with:
          artifacts: EmailModule.zip,Hashes.txt
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      # - name: Publish to PSGallery
      #   run: |
      #     $version = '${{ steps.tag_version.outputs.new_tag }}'
      #     $version = $version  -replace 'v', ''
      #     Publish-Module -Path .\release\EmailModule\$version\ -NuGetApiKey ${{ secrets.PSGALLERY_KEY }} -Verbose
